#SPDX-License-Identifier: MIT-0
---
# vars file for mac-setup
zsh_plugins:
  - zsh-autosuggestions
  - zsh-completions

brews:
  - zsh
  - curl
  - htop
  - python3
  - pygments
  - ripgrep
  - ffind
  - fd
  - fzf
  - pipx
  - aircrack-ng
  - john
  - tcpreplay
  - tcpdump

pipx_packages:
  - git+https://github.com/Pennyw0rth/NetExec