#SPDX-License-Identifier: MIT-0
---
# tasks file for fedora-setup
# Clone zsh-autosuggestion repo into local zsh plugin directory for use
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
- name: Install zsh plugins
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item }}"
    clone: yes
  with_items: "{{ zsh_plugins }}"

- name: Replace GRUB_DEFAULT line in /etc/default/grub.
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: 'GRUB_DEFAULT=saved'
  become: true

- name: Edit grub to remember last choice of grub OS boot menu.
  blockinfile:
    path: /etc/default/grub
    block: |
      # Remember last choice of OS boot functionality
      GRUB_SAVEDEFAULT=true
    insertafter: EOF
  become: true

- name: Update Grub configuration for Fedora.
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: true

- name: Set bluetooth idle timeout to 15 minutes. https://askubuntu.com/questions/1264725/how-to-disable-bluetooth-power-saving
  lineinfile:
    path: /etc/bluetooth/input.conf
    regexp: '^#IdleTimeout=30'
    line: 'IdleTimeout=15'
  become: true

- name: Update bluetooth service configuration.
  command: systemctl restart bluetooth.service
  become: true

- name: Edit dnf config to make it faster.
  blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      fastestmirror=True
      max_parallel_downloads=10
      keepcache=True
    insertafter: EOF
  become: true

- name: Install personalised fedora dnf packages.
  ansible.builtin.package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  ignore_errors: true
  become: true

- name: Install personalised flatpak packages. (Will fail if you are on ubuntu and do not have flatpak manager installed.)
  community.general.flatpak:
    state: present
    method: system
    name: "{{ item }}"
  with_items: "{{ flatpaks }}"
  ignore_errors: true
  become: true

- name: Download vscode directly from source for fedora.
  ansible.builtin.get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64"
    dest: "/tmp/{{ vscode_rpm }}"
  become: true

- name: Install downloaded vscode.
  ansible.builtin.package:
    state: present
    name: "/tmp/{{ vscode_rpm }}"
    disable_gpg_check: "{{ value_for_gpg | d(omit) }}"
  become: true

- name: Install needed pipx packages.
  community.general.pipx:
    state: present
    name: "{{ item }}"
  with_items: "{{ pipx_packages }}"
  ignore_errors: true
  become: true

- name: Add Brave repository
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
  become: true

- name: Import Brave repository key
  ansible.builtin.shell:
    cmd: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  become: true

- name: Install Brave browser
  ansible.builtin.package:
    name: brave-browser
    state: present
  become: true

- name: Replace line in brave-browser.desktop file to enable 2 fingers swipe back and forth gesture. https://gist.github.com/detherminal/1845c794ee3f3cdcc4e7eb713e9ee6fd
  lineinfile:
    path: /usr/share/applications/brave-browser.desktop
    regexp: '^Exec=/usr/bin/brave-browser-stable %U$'
    line: 'Exec=/usr/bin/brave-browser-stable %U --ozone-platform=wayland --enable-features=TouchpadOverscrollHistoryNavigation'
  become: true